---
build_from:
  aarch64: ghcr.io/hassio-addons/phpmyadmin/aarch64:stable
  amd64: ghcr.io/hassio-addons/phpmyadmin/amd64:stable
  armv7: ghcr.io/hassio-addons/phpmyadmin/armv7:stable
codenotary:
  base_image: notary@home-assistant.io
  signer: andrewjswan@addons.community
